// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';

export function IsIpValid(arg1:string):Promise<boolean>;

export function ReadFiles():Promise<Array<network.DocInfo>>;
