// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DirectoryDialog() {
  return window['go']['main']['App']['DirectoryDialog']();
}

export function Export() {
  return window['go']['main']['App']['Export']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCheckedFiles() {
  return window['go']['main']['App']['GetCheckedFiles']();
}

export function GetCheckedFilesCount() {
  return window['go']['main']['App']['GetCheckedFilesCount']();
}

export function GetExportOptions() {
  return window['go']['main']['App']['GetExportOptions']();
}

export function GetFolder(arg1) {
  return window['go']['main']['App']['GetFolder'](arg1);
}

export function GetFolderSelection(arg1) {
  return window['go']['main']['App']['GetFolderSelection'](arg1);
}

export function GetItemSelection(arg1) {
  return window['go']['main']['App']['GetItemSelection'](arg1);
}

export function GetPaths(arg1) {
  return window['go']['main']['App']['GetPaths'](arg1);
}

export function InitExport() {
  return window['go']['main']['App']['InitExport']();
}

export function IsIpValid(arg1) {
  return window['go']['main']['App']['IsIpValid'](arg1);
}

export function OnItemSelect(arg1, arg2) {
  return window['go']['main']['App']['OnItemSelect'](arg1, arg2);
}

export function ReadDocs(arg1) {
  return window['go']['main']['App']['ReadDocs'](arg1);
}

export function SetExportOptions(arg1) {
  return window['go']['main']['App']['SetExportOptions'](arg1);
}
