// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPdfs(arg1) {
  return window['go']['main']['App']['ExportPdfs'](arg1);
}

export function GetElementsByIds(arg1) {
  return window['go']['main']['App']['GetElementsByIds'](arg1);
}

export function GetTabletFolder(arg1) {
  return window['go']['main']['App']['GetTabletFolder'](arg1);
}

export function IsIpValid(arg1) {
  return window['go']['main']['App']['IsIpValid'](arg1);
}

export function ReadTabletDocs(arg1) {
  return window['go']['main']['App']['ReadTabletDocs'](arg1);
}
