name: Wails build

on:
  push:
    tags:
    # Match any new tag
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'rm-importer'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'rm-importer'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'rm-importer'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Build wails
        uses: chopikus/wails-build-action@a9e607df4c313c9a7aaa7b29c61148e77c54ab92
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.22'
          node-version: '20.x'
          macos-build-name: 'rm-importer'
          ubuntu24: "-tags webkit2_41"
